/* Generated by node scripts/build.cjs. Do not edit sw.js directly. */
"use strict";
const RELEASE = "3395deed55adfa64ae1b";
const ASSETS = [
  {
    "path": "./index.html",
    "sha256": "c702f4efd7b80da98a0809bf1d5501ef71b84538f20c4815b9ac207b68a8a232",
    "text": true
  },
  {
    "path": "./app.css",
    "sha256": "1dfbff7b55abb949d0f4d729200bb88cdb03659f4fa869dbffc771f3b48f3a78",
    "text": true
  },
  {
    "path": "./app.js",
    "sha256": "ccb5fc5167ea4fbe9ca819aa2af8dd92becbdc76d06c282f5efcdbca6c3830da",
    "text": true
  },
  {
    "path": "./offline.js",
    "sha256": "2ae138654a14f16db9489ea7b1bb4dc6109a19c4dc3b2c115c3645822f0ab58a",
    "text": true
  },
  {
    "path": "./swim-core.js",
    "sha256": "3124cedb5c28647f1c1ceac36f82fecb93fa1fce1767c28e6019d00e922aae92",
    "text": true
  },
  {
    "path": "./swim-features.js",
    "sha256": "17531c7c3906ffb188e7a2e88342fe3d9f44372d1071c100cd00efdaabc10bab",
    "text": true
  },
  {
    "path": "./manifest.webmanifest",
    "sha256": "647d31c8ab9d2be0454f9c4878fb46127d355783488c8d5af6638ec2fa31e3db",
    "text": true
  },
  {
    "path": "./icons/icon.svg",
    "sha256": "f4dc58057f00c76704458fce170f4c5bea33583cb66fbb60320453fe42e80681",
    "text": true
  },
  {
    "path": "./icons/icon-192.png",
    "sha256": "16f98887a5a7d731d8d5e992b57acdf645ef2c3c8a87d289fe1a693b4401ea8d",
    "text": false
  },
  {
    "path": "./icons/icon-512.png",
    "sha256": "1ae1e6c55cc9c6fa084dc632c63f7d108643418e16c4ee57ed28bf0aba8df07f",
    "text": false
  },
  {
    "path": "./vendor/react-18.2.0.production.min.js",
    "sha256": "4b4969fa4ef3594324da2c6d78ce8766fbbc2fd121fff395aedf997db0a99a06",
    "text": true
  },
  {
    "path": "./vendor/react-dom-18.2.0.production.min.js",
    "sha256": "21758ed084cd0e37e735722ee4f3957ea960628a29dfa6c3ce1a1d47a2d6e4f7",
    "text": true
  }
];
const SCOPE = self.registration.scope;
const CACHE_PREFIX = "swim-offline:" + encodeURIComponent(SCOPE) + ":";
const CACHE_NAME = CACHE_PREFIX + RELEASE;
const READY_KEY = new URL("./__swim_cache_ready__", SCOPE).href;
const resourceURL = (path) => new URL(path, SCOPE).href;
const INDEX_URL = resourceURL("./index.html");
const KNOWN_URLS = new Set(ASSETS.map((asset) => resourceURL(asset.path)));
async function cacheReady() {
  if (!await caches.has(CACHE_NAME)) return false;
  const cache = await caches.open(CACHE_NAME);
  if (!await cache.match(READY_KEY)) return false;
  const entries = await Promise.all(ASSETS.map((asset) => cache.match(resourceURL(asset.path))));
  return entries.every((entry) => entry && entry.status === 200);
}
async function verify(response, asset) {
  if (response.status !== 200) throw new Error("HTTP " + response.status + ": " + asset.path);
  let bytes = await response.clone().arrayBuffer();
  if (asset.text) {
    const text = new TextDecoder().decode(bytes).replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
    bytes = new TextEncoder().encode(text);
  }
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const hash = Array.from(new Uint8Array(digest), (value) => value.toString(16).padStart(2, "0")).join("");
  if (hash !== asset.sha256) throw new Error("Resource version mismatch: " + asset.path);
}
self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    if (await cacheReady()) return;
    const cache = await caches.open(CACHE_NAME);
    try {
      // A partial deployment cannot replace the active, complete cache.
      await Promise.all(ASSETS.map(async (asset) => {
        const url = resourceURL(asset.path);
        const response = await fetch(new Request(url, { cache: "reload", credentials: "same-origin" }));
        await verify(response, asset);
        await cache.put(url, response);
      }));
      await cache.put(READY_KEY, new Response(JSON.stringify({ version: RELEASE }), { headers: { "Content-Type": "application/json" } }));
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // Intentionally do not skipWaiting; updates activate after current tabs close.
  })());
});
async function status() {
  return { type: "SWIM_OFFLINE_STATUS", scope: SCOPE, version: RELEASE, ready: await cacheReady() };
}
self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    if (!await cacheReady()) throw new Error("Incomplete offline cache");
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
    const message = await status();
    const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    clients.filter((client) => client.url.startsWith(SCOPE)).forEach((client) => client.postMessage(message));
  })());
});
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SWIM_CACHE_STATUS") {
    event.waitUntil(status().then((message) => {
      if (event.ports && event.ports[0]) event.ports[0].postMessage(message);
      else if (event.source) event.source.postMessage(message);
    }));
  }
});
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (!url.href.startsWith(SCOPE)) return;
  if (request.mode === "navigate") {
    event.respondWith(caches.open(CACHE_NAME).then(async (cache) => (await cache.match(INDEX_URL)) || fetch(request)));
    return;
  }
  url.search = "";
  url.hash = "";
  if (KNOWN_URLS.has(url.href)) {
    event.respondWith(caches.open(CACHE_NAME).then(async (cache) => (await cache.match(url.href)) || fetch(request)));
  }
});
