/* Generated by node scripts/build.cjs. Do not edit sw.js directly. */
"use strict";
const RELEASE = "e3a6f5100ac451ad3c63";
const ASSETS = [
  {
    "path": "./index.html",
    "sha256": "18353420773dd7bf9cb7a58f41d6fb1d2591217ffdc6ad7f257e6ebc7ee79de3",
    "text": true
  },
  {
    "path": "./app.css",
    "sha256": "2d9190be5685e2194d79bb2ba699631b2cfcb06947280e77ac6e88faee6fc811",
    "text": true
  },
  {
    "path": "./app.js",
    "sha256": "c935090002e504ab56a28b1ab37ed85ef0e5a8de331bf4c0c433304b5d61a5fa",
    "text": true
  },
  {
    "path": "./offline.js",
    "sha256": "fbda92331930b39bd09a5244d47086b0a2e52bfaf2acd01fadd81694ebac2838",
    "text": true
  },
  {
    "path": "./swim-core.js",
    "sha256": "3124cedb5c28647f1c1ceac36f82fecb93fa1fce1767c28e6019d00e922aae92",
    "text": true
  },
  {
    "path": "./swim-features.js",
    "sha256": "17531c7c3906ffb188e7a2e88342fe3d9f44372d1071c100cd00efdaabc10bab",
    "text": true
  },
  {
    "path": "./manifest.webmanifest",
    "sha256": "e0eb6939454160eb8139f211e6341da7dffbd649cf4fdba33e5ac4e085738b4a",
    "text": true
  },
  {
    "path": "./icons/swim-pixel-v2.svg",
    "sha256": "b566ad20ebb18cbf324a113ccadc1649183287954e66c49c058b723e41ba26e8",
    "text": true
  },
  {
    "path": "./icons/swim-pixel-v2-180.png",
    "sha256": "fb6e70f87d5e8b5ababa2dad92db9243572d12159d8a0daa4cd5a7e56f912244",
    "text": false
  },
  {
    "path": "./icons/swim-pixel-v2-192.png",
    "sha256": "ec4fc7a0a6c2efac353434913a62fdc3df12ab0891bd65db23066c80d246517f",
    "text": false
  },
  {
    "path": "./icons/swim-pixel-v2-512.png",
    "sha256": "e512f50fc07de22b5da2b189e6a594cb860aa9253d7ce9e3a52c963a077179c1",
    "text": false
  },
  {
    "path": "./icons/swim-pixel-v2-maskable-512.png",
    "sha256": "e512f50fc07de22b5da2b189e6a594cb860aa9253d7ce9e3a52c963a077179c1",
    "text": false
  },
  {
    "path": "./icons/pixel-icons.svg",
    "sha256": "57448d81e2b29684158eb62a6101f4f44121dc17eae3a0785a4c1be3b475dbe6",
    "text": true
  },
  {
    "path": "./icons/pixel-pool.svg",
    "sha256": "13e8d47c122ffa1d4c4bc54d70468af50356e271ec577fbb638d2940e1fb5bf9",
    "text": true
  },
  {
    "path": "./fonts/swim-pixel.woff2",
    "sha256": "af22be5380c700a634c8995edf4cdc3c99143c9d9c38156e40a557757c6fb3ca",
    "text": false
  },
  {
    "path": "./vendor/react-18.2.0.production.min.js",
    "sha256": "4b4969fa4ef3594324da2c6d78ce8766fbbc2fd121fff395aedf997db0a99a06",
    "text": true
  },
  {
    "path": "./vendor/react-dom-18.2.0.production.min.js",
    "sha256": "21758ed084cd0e37e735722ee4f3957ea960628a29dfa6c3ce1a1d47a2d6e4f7",
    "text": true
  }
];
const SCOPE = self.registration.scope;
const CACHE_PREFIX = "swim-offline:" + encodeURIComponent(SCOPE) + ":";
const CACHE_NAME = CACHE_PREFIX + RELEASE;
const READY_KEY = new URL("./__swim_cache_ready__", SCOPE).href;
const resourceURL = (path) => new URL(path, SCOPE).href;
const INDEX_URL = resourceURL("./index.html");
const KNOWN_URLS = new Set(ASSETS.map((asset) => resourceURL(asset.path)));
async function cacheReady() {
  if (!await caches.has(CACHE_NAME)) return false;
  const cache = await caches.open(CACHE_NAME);
  if (!await cache.match(READY_KEY)) return false;
  const entries = await Promise.all(ASSETS.map((asset) => cache.match(resourceURL(asset.path))));
  return entries.every((entry) => entry && entry.status === 200);
}
async function verify(response, asset) {
  if (response.status !== 200) throw new Error("HTTP " + response.status + ": " + asset.path);
  let bytes = await response.clone().arrayBuffer();
  if (asset.text) {
    const text = new TextDecoder().decode(bytes).replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
    bytes = new TextEncoder().encode(text);
  }
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const hash = Array.from(new Uint8Array(digest), (value) => value.toString(16).padStart(2, "0")).join("");
  if (hash !== asset.sha256) throw new Error("Resource version mismatch: " + asset.path);
}
self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    if (await cacheReady()) return;
    const cache = await caches.open(CACHE_NAME);
    try {
      // A partial deployment cannot replace the active, complete cache.
      await Promise.all(ASSETS.map(async (asset) => {
        const url = resourceURL(asset.path);
        const response = await fetch(new Request(url, { cache: "reload", credentials: "same-origin" }));
        await verify(response, asset);
        await cache.put(url, response);
      }));
      await cache.put(READY_KEY, new Response(JSON.stringify({ version: RELEASE }), { headers: { "Content-Type": "application/json" } }));
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // Installation never activates itself; the safety coordinator below makes that decision.
  })());
});
async function status() {
  return { type: "SWIM_OFFLINE_STATUS", scope: SCOPE, version: RELEASE, ready: await cacheReady() };
}
self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    if (!await cacheReady()) throw new Error("Incomplete offline cache");
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
    const message = await status();
    const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    clients.filter((client) => client.url.startsWith(SCOPE)).forEach((client) => client.postMessage(message));
  })());
});
// A waiting worker only accepts explicit safety votes from every in-scope page.
let activationRound = null;
let activationTask = null;
let retryActivation = false;
let activationAccepted = false;
let roundCounter = 0;
async function scopedClients() {
  const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  return windows.filter((client) => client.url.startsWith(SCOPE));
}
async function updateProgress(blocked) {
  const message = { type: "SWIM_UPDATE_PROGRESS", scope: SCOPE, version: RELEASE, blocked };
  const clients = await scopedClients();
  clients.forEach((client) => client.postMessage(message));
}
async function endRound(round, blocked) {
  if (activationRound !== round) return;
  activationRound = null;
  clearTimeout(round.timer);
  try { await updateProgress(blocked); }
  finally { round.resolve(); }
}
async function finishIfSafe(round) {
  if (activationRound !== round || round.checking || ![...round.votes.values()].every((vote) => vote === true)) return;
  round.checking = true;
  const clients = await scopedClients();
  if (activationRound !== round) return;
  if (clients.some((client) => !round.votes.has(client.id))) {
    // A newly opened page has not voted in this round. Ask again with a fresh roster.
    retryActivation = true;
    await endRound(round, true);
    return;
  }
  if (!await cacheReady()) { await endRound(round, true); return; }
  // A synchronous unsafe vote received during either await revokes earlier consent.
  if (activationRound !== round) return;
  if (clients.some((client) => round.votes.get(client.id) !== true)) { await endRound(round, true); return; }
  activationAccepted = true;
  try { await self.skipWaiting(); }
  catch (error) { activationAccepted = false; await endRound(round, true); throw error; }
  await endRound(round, false);
}
async function activationAttempt() {
  if (!await cacheReady()) { await updateProgress(true); return; }
  const clients = await scopedClients();
  const token = RELEASE + ":" + (++roundCounter) + ":" + crypto.randomUUID();
  let resolve;
  const completion = new Promise((done) => { resolve = done; });
  const round = { token, votes: new Map(clients.map((client) => [client.id, null])), resolve, checking: false, timer: null };
  activationRound = round;
  // Missing/old/background pages never become safe merely because time elapsed.
  round.timer = setTimeout(() => { endRound(round, true).catch(() => {}); }, 8000);
  clients.forEach((client) => client.postMessage({ type: "SWIM_UPDATE_PROBE", token, scope: SCOPE, version: RELEASE }));
  if (clients.length === 0) await finishIfSafe(round);
  await completion;
}
function tryActivation() {
  if (activationAccepted) return Promise.resolve();
  if (activationTask) { retryActivation = true; return activationTask; }
  activationTask = (async () => {
    do {
      retryActivation = false;
      await activationAttempt();
    } while (retryActivation && !activationAccepted);
  })().finally(() => { activationTask = null; });
  return activationTask;
}
async function safetyVote(event) {
  const round = activationRound;
  const data = event.data;
  const client = event.source;
  if (!round || data.token !== round.token || !client || typeof client.url !== "string" || !client.url.startsWith(SCOPE) || !round.votes.has(client.id)) return;
  round.votes.set(client.id, data.safe === true);
  if (data.safe !== true) { await endRound(round, true); return; }
  await finishIfSafe(round);
}

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SWIM_TRY_ACTIVATE" && event.source && typeof event.source.url === "string" && event.source.url.startsWith(SCOPE)) {
    event.waitUntil(tryActivation());
  } else if (event.data && event.data.type === "SWIM_UPDATE_STATE") {
    event.waitUntil(safetyVote(event));
  } else if (event.data && event.data.type === "SWIM_CACHE_STATUS") {
    event.waitUntil(status().then((message) => {
      if (event.ports && event.ports[0]) event.ports[0].postMessage(message);
      else if (event.source) event.source.postMessage(message);
    }));
  }
});
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (!url.href.startsWith(SCOPE)) return;
  if (request.mode === "navigate") {
    event.respondWith(caches.open(CACHE_NAME).then(async (cache) => (await cache.match(INDEX_URL)) || fetch(request)));
    return;
  }
  url.search = "";
  url.hash = "";
  if (KNOWN_URLS.has(url.href)) {
    event.respondWith(caches.open(CACHE_NAME).then(async (cache) => (await cache.match(url.href)) || fetch(request)));
  }
});
